#===================================
#=                                 =
#=    Plugin for Zyaba project     =
#=                                 =
#=        by MrBedrockpy           =
#=                                 =
#===================================

parameters:
  minradius: 5
  vip:
    maxradius:
    count: 3
  premium:
    maxradius:
    count: 4
  deluxe:
    maxradius:
    count: 6
  quantum:
    maxradius:
    count: 8
  sponsor:
    maxradius:
    count: 10


messages:
  creation-success: "Регион успешно создан!"
  deletion-success: "Регион успешно удален!"
  creation-error: "При создании региона возникла ошибка!"
  deletion-error: "При удалении региона возникла ошибка!"

regions:
  spawn:
    center:
      - 0
      - 75
      - 0
    radius: 35